name: Deploy App

on:
  workflow_dispatch:

jobs:

# ======================
# BUILD IMAGES
# ======================
  build:
    runs-on: r2

    steps:
      - uses: actions/checkout@v4

      - name: Build Backend Image
        run: docker build -t zeina-backend:latest -f backend/Dockerfile backend

      - name: Build Frontend Image
        run: |
          docker build \
            --build-arg REACT_APP_BACKEND_URL=http://172.31.13.167:8002/api \
            -t zeina-frontend:latest \
            -f frontend/Dockerfile frontend

      - name: Save Images
        run: |
          docker save zeina-backend:latest -o backend.tar
          docker save zeina-frontend:latest -o frontend.tar

# ======================
# TRIVY BACKEND (ONLY LIBS)
# ======================
  trivy-backend:
    runs-on: r2
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Load Backend Image
        run: docker load -i backend.tar

      - name: Trivy Backend Scan
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --vuln-type library \
            --severity CRITICAL \
            --exit-code 1 \
            zeina-backend:latest

# ======================
# TRIVY FRONTEND (ONLY LIBS)
# ======================
  trivy-frontend:
    runs-on: r2
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Load Frontend Image
        run: docker load -i frontend.tar

      - name: Trivy Frontend Scan
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --vuln-type library \
            --severity CRITICAL \
            --exit-code 1 \
            zeina-frontend:latest

# ======================
# DEPLOY (RUNS ONLY IF SCANS PASS)
# ======================
  deploy:
    runs-on: r2
    needs: [trivy-backend, trivy-frontend]

    steps:
      - name: Deploy Containers
        run: |
          docker compose down
          docker compose up -d --force-recreate
