name: Deploy App

on:
  workflow_dispatch:

jobs:

# ======================
# BUILD IMAGES
# ======================
  build:
    runs-on: r2

    steps:
      - uses: actions/checkout@v4

      - name: Build Backend Image
        run: docker build -t zeina-backend:latest -f backend/Dockerfile backend

      - name: Build Frontend Image
        run: |
          docker build \
            --build-arg REACT_APP_BACKEND_URL=http://172.31.13.167:8002/api \
            -t zeina-frontend:latest \
            -f frontend/Dockerfile frontend

      - name: Save Images
        run: |
          docker save zeina-backend:latest -o backend.tar
          docker save zeina-frontend:latest -o frontend.tar

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-image
          path: backend.tar

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-image
          path: frontend.tar


# ======================
# TRIVY BACKEND SCAN
# ======================
  trivy-backend:
    runs-on: r2
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-image

      - name: Debug files
        run: ls -lah

      - name: Load Backend Image
        run: docker load -i backend.tar

      - name: Run Trivy Backend Report
        run: |
          mkdir -p reports

          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $PWD/reports:/reports \
            aquasec/trivy:latest image \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --format json \
            --output /reports/backend-report.json \
            zeina-backend:latest


# ======================
# TRIVY FRONTEND SCAN
# ======================
  trivy-frontend:
    runs-on: r2
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-image

      - name: Debug files
        run: ls -lah

      - name: Load Frontend Image
        run: docker load -i frontend.tar

      - name: Run Trivy Frontend Report
        run: |
          mkdir -p reports

          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $PWD/reports:/reports \
            aquasec/trivy:latest image \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --format json \
            --output /reports/frontend-report.json \
            zeina-frontend:latest


# ======================
# BACKUP
# ======================
  backup:
    runs-on: r2
    needs: [build, trivy-backend, trivy-frontend]

    steps:
      - name: Create Backup Folder
        run: mkdir -p /home/zeina/backups/mern/$(date +%Y%m%d-%H%M%S)

      - name: Save Images
        run: |
          docker save zeina-backend:latest -o /home/zeina/backups/mern/backend.tar
          docker save zeina-frontend:latest -o /home/zeina/backups/mern/frontend.tar


# ======================
# DEPLOY
# ======================
  deploy:
    runs-on: r2
    needs: backup

    steps:
      - name: Deploy Containers
        run: |
          docker compose down
          docker compose up -d --force-recreate


# ======================
# OWASP ZAP SECURITY SCAN
# ======================
  owasp-zap:
    runs-on: r2
    needs: deploy

    steps:
      - name: Create ZAP report folder
        run: mkdir -p zap-reports

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm \
            -v $PWD/zap-reports:/zap/wrk:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://172.31.13.167:3000 \
            -r zap-report.html \
            -J zap-report.json \
            -w zap-warnings.md \
            -I

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-reports
