
name: CI/CD

on:
  workflow_dispatch:

env:
  APP_DIR: /home/gaelle/g_app/todo-app
  BACKUP_DIR: /home/gaelle/g_app/backups

jobs:
  deploy:
    runs-on: [self-hosted, gaelle]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate image version
        run: |
          echo "VERSION=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      # Create backup folders
      - name: Create backup directory
        run: |
          mkdir -p $BACKUP_DIR/versions/$VERSION/backend
          mkdir -p $BACKUP_DIR/versions/$VERSION/frontend

      # Save previous latest images
      - name: Backup current images
        run: |
          if docker image inspect mern-backend:latest > /dev/null 2>&1; then
            docker save \
              -o $BACKUP_DIR/versions/$VERSION/backend/backend.tar \
              mern-backend:latest
          fi

          if docker image inspect mern-frontend:latest > /dev/null 2>&1; then
            docker save \
              -o $BACKUP_DIR/versions/$VERSION/frontend/frontend.tar \
              mern-frontend:latest
          fi

      # Stop old containers
      - name: Stop old containers
        run: |
          docker compose -f $APP_DIR/docker-compose.yml down || true

      # Remove previous latest images
      - name: Remove old latest images
        run: |
          docker rmi mern-backend:latest || true
          docker rmi mern-frontend:latest || true

      # Build new latest images
      - name: Build backend image
        run: |
          docker build -t mern-backend:latest ./backend

      - name: Build frontend image
        run: |
          docker build -t mern-frontend:latest ./frontend

      # Deploy
      - name: Start containers
        run: |
          docker compose -f $APP_DIR/docker-compose.yml up -d

      - name: Show running containers
        run: docker ps

      - name: Show backup folders
        run: |
          ls -R $BACKUP_DIR

