
name: CI/CD

on:
  workflow_dispatch:

env:
  APP_DIR: /home/gaelle/g_app/todo-app
  BACKUP_DIR: /home/gaelle/g_app/backups

jobs:
  # 1. PREPARE
  prepare:
    runs-on: [self-hosted, gaelle]

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate image version
        id: version
        run: |
          VERSION=$(date +'%Y%m%d-%H%M%S')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  # 2. BACKUP
  backup:
    runs-on: [self-hosted, gaelle]
    needs: prepare

    steps:
      - name: Create backup directory
        run: |
          mkdir -p $BACKUP_DIR/versions/${{ needs.prepare.outputs.version }}/backend
          mkdir -p $BACKUP_DIR/versions/${{ needs.prepare.outputs.version }}/frontend

      - name: Backup current images
        run: |
          if docker image inspect mern-backend:latest > /dev/null 2>&1; then
            docker save \
              -o $BACKUP_DIR/versions/${{ needs.prepare.outputs.version }}/backend/backend.tar \
              mern-backend:latest
          fi

          if docker image inspect mern-frontend:latest > /dev/null 2>&1; then
            docker save \
              -o $BACKUP_DIR/versions/${{ needs.prepare.outputs.version }}/frontend/frontend.tar \
              mern-frontend:latest
          fi
 
  # 3. SONARQUBE
#  sonar:
#    runs-on: [self-hosted, gaelle]
#    needs: backup

#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0

      # FRONTEND SCAN
#      - name: Sonar Frontend
#        uses: SonarSource/sonarqube-scan-action@v6
#        env:
#          SONAR_TOKEN: ${{ secrets.G_SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.G_SONAR_HOST_URL }}
#        with:
#          args: >
#            -Dsonar.projectKey=mern-todo-app
#            -Dsonar.projectName="MERN Todo Frontend"
#            -Dsonar.sources=frontend/src
#            -Dsonar.sourceEncoding=UTF-8
#            -Dsonar.exclusions=**/node_modules/**

      # BACKEND SCAN
#      - name: Sonar Backend
#        uses: SonarSource/sonarqube-scan-action@v6
#        env:
#          SONAR_TOKEN: ${{ secrets.GG_SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.GG_SONAR_HOST_URL }}
#        with:
#          args: >
#            -Dsonar.projectKey=mern-todo-app-backend
#            -Dsonar.projectName="MERN Todo Backend"
#            -Dsonar.sources=backend
#            -Dsonar.sourceEncoding=UTF-8
#            -Dsonar.exclusions=**/node_modules/**
  
  # 4. STOP OLD CONTAINERS
  stop_containers:
    runs-on: [self-hosted, gaelle]
    needs: backup

    steps:
      - name: Stop old containers
        run: |
          docker compose -f $APP_DIR/docker-compose.yml down || true

  # 4. REMOVE OLD IMAGES
  remove_old_images:
    runs-on: [self-hosted, gaelle]
    needs: stop_containers

    steps:
      - name: Remove old backend image
        run: |
          docker rmi mern-backend:latest || true

      - name: Remove old frontend image
        run: |
          docker rmi mern-frontend:latest || true

  # 5. BUILD BACKEND
  build_backend:
    runs-on: [self-hosted, gaelle]
    needs: remove_old_images

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend image
        run: |
          docker build -t mern-backend:latest ./backend

  # 6. BUILD FRONTEND
  build_frontend:
    runs-on: [self-hosted, gaelle]
    needs: remove_old_images
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Build frontend image
        run: |
          docker build \
            --build-arg REACT_APP_BACKEND_URL=http://172.31.13.167:8000 \
            -t mern-frontend:latest ./frontend

  # 7. TRIVY SECURITY SCAN
  trivy_backend:
    runs-on: [self-hosted, gaelle]
    needs: build_backend
  
    steps:
      - name: Ensure Trivy Docker Image Exists
        run: docker pull aquasec/trivy:latest
  
      - name: Backend - Warning HIGH
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --severity HIGH \
            --exit-code 0 \
            mern-backend:latest
  
      - name: Backend - Fail CRITICAL
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --pkg-types os \
            --severity CRITICAL \
            --exit-code 1 \
            mern-backend:latest
       
  trivy_frontend:
    runs-on: [self-hosted, gaelle]
    needs: build_frontend
  
    steps:
      - name: Ensure Trivy Docker Image Exists
        run: docker pull aquasec/trivy:latest
  
      - name: Frontend - Warning HIGH
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --severity HIGH \
            --exit-code 0 \
            mern-frontend:latest
  
      - name: Frontend - Fail CRITICAL
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --severity CRITICAL \
            --exit-code 1 \
            mern-frontend:latest

  # 8. DEPLOY
  deploy:
    runs-on: [self-hosted, gaelle]
    needs: [trivy_backend, trivy_frontend]

    steps:
      - name: Start containers
        run: |
          docker compose -f $APP_DIR/docker-compose.yml up -d

  # 9. VERIFY
  verify:
    runs-on: [self-hosted, gaelle]
    needs: deploy

    steps:
      - name: Show running containers
        run: docker ps

      - name: Show Docker images
        run: |
          docker images | grep mern

      - name: Show backup folders
        run: |
          ls -R $BACKUP_DIR

